<a href="https://colab.research.google.com/github/Vdharmaram/Neural-Networks-and-Deep-Learning-ICP2/blob/main/700762267_ICP2_Vishali_Dharmaram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [12]:
class Employee:#Create an Employee class
    employeeCount=0 #employeeConut is used to keep track of numner of employee objects
    salaraySum=0 #salarySum is used to take the average of the salaries of the Employee object
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employeeCount+= 1
        Employee.salaraySum+=self.salary # Accessing the class-level salarySum
    def avg(self):
        return Employee.salaraySum/Employee.employeeCount
    def displayCount(self): #One of the functions in Employee class
        print ("Total Employee %d" % Employee.employeeCount)
    def displayEmployee(self):#another function for employee class
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("supriya","vedere",5000,"Research")#Employee objects creation with intialization
emp2 = Employee("krishna","Singarapu",8000,"Development")
print("avg:",emp2.avg())#calling average function
class FulltimeEmployee(Employee):#FulltimeEmployee class with Employee as its parent class
    def __init__(self,name,family,salary,department,c_name):#constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):#one of the FulltimeEmployee class function
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
vd=FulltimeEmployee("Vishali","Dharmaram",4000,"Backend","Google")#FultimeEmployee object
vd.setCompany("Samsung")#calling the member functions of FulltimeEmploye and Employee
vd.getCompany(),vd.displayEmployee(),emp1.displayCount()

avg: 6500.0
Name :  Vishali Family:  Dharmaram Salary:  4000 department: Backend
Total Employee 3


('Samsung', None, None)

2. Numpy  Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [11]:
import numpy as np #importing numpy library
v=np.arange(1,21,dtype=float) #creating a numpy v with arange function
print(v)
v=v.reshape(4,5)#reshaping the v with reshape() function
print(v)
v=np.where(np.isin(v,v.max(axis=1)),0,v)#finding the max values in row and replacing them with zero using np.where() and np.max() function v

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.],
       [16., 17., 18., 19.,  0.]])

https://drive.google.com/file/d/11q7O07MgpUajz8lnDtZZhVkyeBQ_PevB/view?usp=sharing